name: Build

on:
    workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [windows-latest, ubuntu-latest]
      steps:
        - uses: actions/checkout@v3
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18
        - name: Install Yarn
          run: npm install -g yarn@1.22.22
        - name: Build ${{ matrix.os }}
          run: node cmd/${{ matrix.os }}/build.js
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  